services:
    anime_db.form.type.image:
        class: AnimeDb\Bundle\FormTypeImageBundle\Form\Type\ImageType
        tags:
            - { name: form.type, alias: image }

    anime_db.form.type.image_collection:
        class: AnimeDb\Bundle\FormTypeImageBundle\Form\Type\ImageCollectionType
        arguments: [ '%upload.files_limit%' ]
        tags:
            - { name: form.type, alias: image_collection }

    anime_db.form.type.image_handler:
        class: AnimeDb\Bundle\FormTypeImageBundle\Form\Type\Handler\ImageHandler
        tags:
            - { name: form.type, alias: anime_db_image_handler }

    anime_db.form.type.image_collection_handler:
        class: AnimeDb\Bundle\FormTypeImageBundle\Form\Type\Handler\ImageCollectionHandler
        arguments: [ '%upload.files_limit%' ]
        tags:
            - { name: form.type, alias: anime_db_image_collection_handler }

    anime_db.uploader:
        class: AnimeDb\Bundle\FormTypeImageBundle\Service\Uploader
        arguments: [ '%upload.dir%', '%upload.web_path%' ]
